#!/usr/bin/env python3
"""Generate bench/ground-truth.tsv from adler-core/data/sites.json.

For each site in bench/sites.tsv, look up its `known_present` entries in the
Adler registry and emit `(username, canonical_site, found)` triples. Add
`(synthetic_nonsense_user, canonical_site, notfound)` triples for every
nonsense username in bench/synthetic-nonsense.txt across every canonical site.

The output is `bench/ground-truth.tsv`. Re-run after editing sites.tsv or
synthetic-nonsense.txt.
"""

from __future__ import annotations

import csv
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
BENCH_DIR = Path(__file__).resolve().parent
SITES_JSON = REPO_ROOT / "adler-core" / "data" / "sites.json"
SITES_TSV = BENCH_DIR / "sites.tsv"
NONSENSE_FILE = BENCH_DIR / "synthetic-nonsense.txt"
GROUND_TRUTH_TSV = BENCH_DIR / "ground-truth.tsv"


def read_tsv_rows(path: Path) -> list[list[str]]:
    rows = []
    for line in path.read_text().splitlines():
        if not line or line.startswith("#"):
            continue
        rows.append(line.split("\t"))
    return rows


def read_nonsense(path: Path) -> list[str]:
    out = []
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        out.append(line)
    return out


def known_present_users(site: dict) -> list[str]:
    kp = site.get("known_present")
    if kp is None:
        return []
    if isinstance(kp, str):
        return [kp]
    if isinstance(kp, list):
        return [u for u in kp if isinstance(u, str)]
    return []


def main() -> int:
    if not SITES_JSON.exists():
        print(f"missing {SITES_JSON}", file=sys.stderr)
        return 1

    registry = json.loads(SITES_JSON.read_text())
    sites_by_name = {s["name"]: s for s in registry["sites"]}

    canonical_rows = read_tsv_rows(SITES_TSV)
    nonsense_users = read_nonsense(NONSENSE_FILE)

    rows: list[tuple[str, str, str]] = []

    # Positive labels — every (kp user, canonical site) pair where the user
    # is in that site's known_present.
    for canonical, adler_name, _url in canonical_rows:
        site = sites_by_name.get(adler_name)
        if site is None:
            print(
                f"warning: {canonical} maps to '{adler_name}' which is not in "
                f"the Adler registry — skipping",
                file=sys.stderr,
            )
            continue
        for user in known_present_users(site):
            rows.append((user, canonical, "found"))

    # Negative labels — every synthetic-nonsense user × every canonical site.
    canonical_names = [c for c, _, _ in canonical_rows]
    for user in nonsense_users:
        for canonical in canonical_names:
            rows.append((user, canonical, "notfound"))

    # De-dup (a user might appear in known_present for the same site twice
    # under different aliases, in theory).
    seen: set[tuple[str, str, str]] = set()
    deduped: list[tuple[str, str, str]] = []
    for r in rows:
        if r in seen:
            continue
        seen.add(r)
        deduped.append(r)

    with GROUND_TRUTH_TSV.open("w", newline="") as f:
        f.write("# Generated by bench/derive-ground-truth.py — do not edit by hand.\n")
        f.write("# username\tsite\texpected\n")
        writer = csv.writer(f, delimiter="\t")
        for r in deduped:
            writer.writerow(r)

    # Summary
    users = sorted({u for u, _, _ in deduped})
    pos = sum(1 for _, _, e in deduped if e == "found")
    neg = sum(1 for _, _, e in deduped if e == "notfound")
    print(
        f"wrote {len(deduped)} triples to {GROUND_TRUTH_TSV.relative_to(REPO_ROOT)} "
        f"({pos} found, {neg} notfound) over {len(users)} usernames",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
